const adminControler=require('../controller/adminControler')
const is_Admin = require("../middleware/admin_auth")
var express = require("express")
var router = express.Router()
router.get("/", adminControler.adminLoginPage)
router.get("/loadDashboard", adminControler.loadDashBoardAgain)
router.post("/dashboard", adminControler.loadDashBoard)
router.get("/userList", is_Admin, adminControler.userList)
router.get("/block", is_Admin, adminControler.block)
router.get("/unblock", is_Admin, adminControler.unblock)
router.get("/acceptCancelation", is_Admin, adminControler.acceptCancel)
router.get("/rejectCancelation", is_Admin, adminControler.rejectCancel)
router.get("/acceptReturn", is_Admin, adminControler.acceptReturn)
router.get("/loadNotification", is_Admin, adminControler.notificationLoad)
router.post("/fetchData/:time", adminControler.fetchDataGraph)
router.post("/search", is_Admin, adminControler.search)
router.post("/orderSearch", is_Admin, adminControler.orderSearch)
router.get("/logout", is_Admin, adminControler.adminLogout)
module.exports=router
