const cartControler=require('../controller/cartController')
const is_User = require("../middleware/customer_auth")
const is_Blocked = require("../middleware/customer_block")
var express = require("express")
var router = express.Router()
router.get("/addToCart",is_User,is_Blocked, cartControler.addToCart)
router.get("/viewCart",is_User,is_Blocked,cartControler.viewCart)
router.get("/updateQuantity",is_User,is_Blocked,cartControler.updateQuantity)
router.get("/getProductDetails",is_User,is_Blocked,cartControler.getProductDetails)
router.get("/getProductInfo",is_User,is_Blocked,cartControler.getProductInfo)
router.get("/removeCart",is_User,is_Blocked,cartControler.removeCart)
router.get("/checkOut",is_User,is_Blocked, cartControler.checkOut)
router.get("/getQuantity",is_User,is_Blocked, cartControler.getQuantity)
router.get("/cartNumberCount",is_User,is_Blocked,cartControler.countCartNumber)
module.exports=router