const is_Admin = require("../middleware/admin_auth")
const couponController = require("../controller/couponController")
const is_User = require("../middleware/customer_auth")
const is_Blocked = require("../middleware/customer_block")
var express = require("express")
var router = express.Router()
router.get("/couponList", is_Admin, couponController.addCoupon)
router.post("/addingCoupon", is_Admin, couponController.addingCoupon)
router.get("/editCoupon", is_Admin, couponController.editCoupon)
router.post("/editingCoupon", is_Admin, couponController.editingCoupon)
router.get("/deleteCoupon", is_Admin, couponController.deleteCoupon)
router.post("/applyingCoupon",is_User,is_Blocked,couponController.applyingCoupon)
router.get("/showCoupon",is_User,is_Blocked,couponController.showCoupon)
module.exports = router
